name: 'Setup Cloudflare SSH'
description: 'Sets up SSH connection through Cloudflare tunnel'
inputs:
  ssh-private-key:
    description: 'SSH private key for authentication'
    required: true
  server-hostname:
    description: 'Cloudflare tunnel hostname (e.g., thakii-02.fds-1.com)'
    required: true
  server-user:
    description: 'SSH username'
    required: true
    default: 'ec2-user'
  host-alias:
    description: 'SSH host alias to use in commands'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Disable IPv6 and Install cloudflared
      run: |
        echo "🔧 Disabling IPv6..."
        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
        sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
        echo "📥 Installing cloudflared..."
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb
        cloudflared --version
        echo "✅ cloudflared installed with IPv6 disabled"
      shell: bash
    
    - name: Setup SSH Key
      run: |
        echo "🔑 Setting up SSH private key..."
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        
        # Save the SSH private key
        echo "${{ inputs.ssh-private-key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        echo "✅ SSH key configured"
      shell: bash
    
    - name: Configure SSH with cloudflared
      run: |
        echo "⚙️  Configuring SSH for Cloudflare tunnel..."
        
        # The tunnel now uses tcp:// protocol, so we use cloudflared access tcp
        # Force IPv4 with --edge-ip-version 4
        cat >> ~/.ssh/config << 'EOF'
        Host ${{ inputs.host-alias }}
          HostName ${{ inputs.server-hostname }}
          User ${{ inputs.server-user }}
          IdentityFile ~/.ssh/id_rsa
          ProxyCommand cloudflared access ssh --hostname %h
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
          ServerAliveInterval 30
          ServerAliveCountMax 3
        EOF
        echo "✅ SSH config created"
        echo ""
        echo "📋 SSH configuration:"
        cat ~/.ssh/config
      shell: bash
    
    - name: Test SSH connection
      run: |
        echo "🔍 Testing SSH connection..."
        if ssh ${{ inputs.host-alias }} "echo '✅ SSH connection successful'"; then
          echo "🎉 SSH tunnel is working!"
        else
          echo "❌ SSH connection failed"
          exit 1
        fi
      shell: bash
