name: 'Setup Cloudflare SSH'
description: 'Sets up SSH connection through Cloudflare tunnel'
inputs:
  ssh-private-key:
    description: 'SSH private key for authentication'
    required: true
  server-hostname:
    description: 'Cloudflare tunnel hostname (e.g., thakii-02.fds-1.com)'
    required: true
  server-user:
    description: 'SSH username'
    required: true
    default: 'ec2-user'
  host-alias:
    description: 'SSH host alias to use in commands'
    required: true
  cf-service-token-id:
    description: 'Cloudflare service token ID'
    required: true
  cf-service-token-secret:
    description: 'Cloudflare service token secret'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Disable IPv6 and Install cloudflared
      run: |
        echo "🔧 Disabling IPv6..."
        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
        sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
        echo "📥 Installing cloudflared..."
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb
        cloudflared --version
        echo "✅ cloudflared installed with IPv6 disabled"
      shell: bash
    
    - name: Setup SSH Key
      run: |
        echo "🔑 Setting up SSH private key..."
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        
        # Save the SSH private key
        echo "${{ inputs.ssh-private-key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        echo "✅ SSH key configured"
      shell: bash
    
    - name: Configure SSH with cloudflared service token
      run: |
        echo "⚙️  Configuring SSH for Cloudflare tunnel with service token..."
        
        # Use cloudflared access tcp with service token authentication
        # This bypasses IPv6 DNS issues by using service token auth
        cat >> ~/.ssh/config << 'EOF'
        Host ${{ inputs.host-alias }}
          HostName ${{ inputs.server-hostname }}
          User ${{ inputs.server-user }}
          IdentityFile ~/.ssh/id_rsa
          ProxyCommand cloudflared access tcp --hostname %h --url tcp://127.0.0.1:2222 --service-token-id ${{ inputs.cf-service-token-id }} --service-token-secret ${{ inputs.cf-service-token-secret }}
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
          ServerAliveInterval 30
          ServerAliveCountMax 3
        EOF
        echo "✅ SSH config created"
        echo ""
        echo "📋 SSH configuration:"
        cat ~/.ssh/config
      shell: bash
    
    - name: Test SSH connection
      run: |
        echo "🔍 Testing SSH connection with 60s timeout..."
        echo "Command: ls -la / (list root directory)"
        echo ""
        
        # Simple test: list root directory
        if timeout 60s ssh -v -o ConnectTimeout=30 ${{ inputs.host-alias }} "ls -la /" 2>&1 | tee /tmp/ssh_debug.log; then
          echo ""
          echo "🎉 SSH tunnel is working!"
        else
          SSH_EXIT=$?
          echo "❌ SSH connection failed or timed out (exit code: $SSH_EXIT)"
          echo ""
          echo "Last 30 lines of SSH debug output:"
          tail -30 /tmp/ssh_debug.log
          exit 1
        fi
      shell: bash
