name: 'Setup Cloudflare SSH'
description: 'Sets up SSH connection through Cloudflare tunnel'
inputs:
  ssh-private-key:
    description: 'SSH private key for authentication'
    required: true
  server-hostname:
    description: 'Cloudflare tunnel hostname (e.g., jaiker-ssh.fanusdigital.site)'
    required: true
  server-user:
    description: 'SSH username'
    required: true
    default: 'ec2-user'
  host-alias:
    description: 'SSH host alias to use in commands'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup SSH Key
      run: |
        echo "🔑 Setting up SSH private key..."
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        
        # Save the SSH private key
        echo "${{ inputs.ssh-private-key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Verify key format
        echo "✅ SSH key configured"
        echo "Key fingerprint:"
        ssh-keygen -l -f ~/.ssh/id_rsa || echo "Could not generate fingerprint"
      shell: bash
    
    - name: Configure SSH
      run: |
        echo "⚙️  Configuring SSH for Cloudflare tunnel..."
        cat >> ~/.ssh/config << 'EOF'
        Host ${{ inputs.host-alias }}
          HostName ${{ inputs.server-hostname }}
          User ${{ inputs.server-user }}
          IdentityFile ~/.ssh/id_rsa
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
          ServerAliveInterval 30
          ServerAliveCountMax 3
          ConnectTimeout 60
          Port 22
        EOF
        echo "✅ SSH config created"
        echo ""
        echo "📋 SSH configuration:"
        cat ~/.ssh/config
      shell: bash
    
    - name: Test SSH connection
      run: |
        echo "🔍 Testing SSH connection..."
        if ssh ${{ inputs.host-alias }} "echo '✅ SSH connection successful'"; then
          echo "🎉 SSH tunnel is working!"
        else
          echo "❌ SSH connection failed"
          exit 1
        fi
      shell: bash
